docsPath: ./myapp-docs
structure:
  summary: toc.md
  assets: assets
  docTreeOptions:
    openApiTryIt: true
    showDownloadOpenApiFile: false
    shouldCreateSchemaCategory: false
footerTemplate: ""
headerIncludes: ""
