docsPath: ./myapp-docs
structure:
  summary: toc.md
  assets: assets
  docTreeOptions:
    openApiTryIt: false
    showDownloadOpenApiFile: false
    shouldCreateSchemaCategory: true
footerTemplate: ""
headerIncludes: ""
