docsPath: ./new_site
structure:
  summary: toc.md
  assets: assets
  docTreeOptions:
    showDownloadOpenApiFile: true
    shouldCreateSchemaCategory: true

    openApiLanguageExamples:
      - value: python
        label: py
      - value: javascript
        label: js
footerTemplate: ""
headerIncludes: ""
